// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrnaAngular.Data;

namespace UrnaAngular.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210531115459_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UrnaAngular.Models.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Legenda")
                        .HasColumnType("int");

                    b.Property<string>("NomePresidente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeVice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Partido")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Candidatos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCadastro = new DateTime(2021, 5, 31, 8, 54, 58, 355, DateTimeKind.Local).AddTicks(6406),
                            Legenda = 0,
                            NomePresidente = "Branco",
                            NomeVice = "Branco",
                            Partido = "Branco"
                        },
                        new
                        {
                            Id = 2,
                            DataCadastro = new DateTime(2021, 5, 31, 8, 54, 58, 357, DateTimeKind.Local).AddTicks(7814),
                            Legenda = 99,
                            NomePresidente = "Nulo",
                            NomeVice = "Nulo",
                            Partido = "Nulo"
                        },
                        new
                        {
                            Id = 3,
                            DataCadastro = new DateTime(2021, 5, 31, 8, 54, 58, 357, DateTimeKind.Local).AddTicks(7858),
                            Legenda = 12,
                            NomePresidente = "Lula",
                            NomeVice = "Madona",
                            Partido = "PT"
                        },
                        new
                        {
                            Id = 4,
                            DataCadastro = new DateTime(2021, 5, 31, 8, 54, 58, 357, DateTimeKind.Local).AddTicks(7862),
                            Legenda = 45,
                            NomePresidente = "FHC",
                            NomeVice = "Mickey",
                            Partido = "PSDB"
                        },
                        new
                        {
                            Id = 5,
                            DataCadastro = new DateTime(2021, 5, 31, 8, 54, 58, 357, DateTimeKind.Local).AddTicks(7864),
                            Legenda = 17,
                            NomePresidente = "Jumento",
                            NomeVice = "Capitao Jegue",
                            Partido = "PSL"
                        });
                });

            modelBuilder.Entity("UrnaAngular.Models.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<int>("QtdVotos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.ToTable("Votos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CandidatoId = 1,
                            QtdVotos = 1
                        },
                        new
                        {
                            Id = 2,
                            CandidatoId = 2,
                            QtdVotos = 1
                        },
                        new
                        {
                            Id = 3,
                            CandidatoId = 5,
                            QtdVotos = 1
                        },
                        new
                        {
                            Id = 4,
                            CandidatoId = 3,
                            QtdVotos = 1
                        },
                        new
                        {
                            Id = 5,
                            CandidatoId = 3,
                            QtdVotos = 1
                        },
                        new
                        {
                            Id = 6,
                            CandidatoId = 4,
                            QtdVotos = 1
                        },
                        new
                        {
                            Id = 7,
                            CandidatoId = 4,
                            QtdVotos = 1
                        },
                        new
                        {
                            Id = 8,
                            CandidatoId = 3,
                            QtdVotos = 1
                        },
                        new
                        {
                            Id = 9,
                            CandidatoId = 5,
                            QtdVotos = 1
                        },
                        new
                        {
                            Id = 10,
                            CandidatoId = 3,
                            QtdVotos = 1
                        },
                        new
                        {
                            Id = 11,
                            CandidatoId = 2,
                            QtdVotos = 1
                        },
                        new
                        {
                            Id = 12,
                            CandidatoId = 3,
                            QtdVotos = 1
                        });
                });

            modelBuilder.Entity("UrnaAngular.Models.Voto", b =>
                {
                    b.HasOne("UrnaAngular.Models.Candidato", "Candidato")
                        .WithMany("Votos")
                        .HasForeignKey("CandidatoId");

                    b.Navigation("Candidato");
                });

            modelBuilder.Entity("UrnaAngular.Models.Candidato", b =>
                {
                    b.Navigation("Votos");
                });
#pragma warning restore 612, 618
        }
    }
}
